DrumBeat/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('drumbeatapp/', include('drumbeatapp.urls'))
]

drumbeatapp/urls.py
from django.urls import path
from . import views


app_name = 'drumbeatapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('get_instruments/', views.get_instruments, name='get_instruments'),
    path('get_scores/', views.get_scores, name='get_scores'),
    path('save_score', views.save_score, name='save_score'),
    path('login_page/', views.login_page, name='login_page'),
    path('protected/', views.protected, name='protected'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('register_page/', views.register_page, name='register_page')
]

drumbeatapp/models.py
from django.db import models
from django.contrib.auth.models import User



class Instrument(models.Model):
    name = models.CharField(max_length=30)
    sound = models.CharField(max_length=2000)


    def __str__(self):
        return self.name




class Score(models.Model):
    name = models.CharField(max_length=30)
    score_data = models.TextField()
    user = models.ForeignKey(User, on_delete=models.PROTECT)


    def __str__(self):
        return self.name

drumbeatapp/views.py
import requests
import json
import django.contrib.auth
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from .models import Instrument, Score
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User





def index(request):
    return render(request, 'drumbeatapp/index.html')


def get_instruments(request):
    instruments = Instrument.objects.all()
    data = []
    for instrument in instruments:
        data.append({
            'id': instrument.id,
            'name': instrument.name,
            'sound': instrument.sound,
        })
    return JsonResponse({'instruments': data})


def get_scores(request):
    scores = Score.objects.all().filter(user=request.user)
    data = []
    for score in scores:
        print(json.loads(score.score_data))
        score_data = json.loads(score.score_data)
        data.append(score_data)
    return JsonResponse({'scores': data})


def save_score(request):
    data = json.loads(request.body)
    data = json.loads(data["score"])
    name = data["score_name"]
    # if name == '':
    #     return HttpResponse('not ok')
    score = Score(name=name, score_data=json.dumps(data), user=request.user)
    score.save()
    return HttpResponse("ok")


def login_register(request):
    return render(request, 'drumbeatapp/login_register.html')


def login_page(request):
    return render(request, 'drumbeatapp/login.html')


def register_page(request):
    return render(request, 'drumbeatapp/register.html')


@login_required
def protected(request):
    score_name = request.POST['score_name']
    return render(request, 'drumbeatapp/index.html')


def login(request):
    username = request.POST['username']
    password = request.POST['password']
    user = django.contrib.auth.authenticate(request, username=username, password=password)
    if user is None: # authenticiation failed, send them back to the login/register page
        print("User was None, redirecting")
        return HttpResponseRedirect(reverse('drumbeatapp:login_page'))
    # authentication succeeded, send them to the protected page
    django.contrib.auth.login(request, user)
    return HttpResponseRedirect(reverse('drumbeatapp:index'))


def register(request):
    username = request.POST['username']
    email = request.POST['email']
    password = request.POST['password']
    user = User.objects.create_user(username, email, password)
    django.contrib.auth.login(request, user)
    return HttpResponseRedirect(reverse('drumbeatapp:index'))


def logout(request):
    django.contrib.auth.logout(request)
    return HttpResponseRedirect(reverse('drumbeatapp:login_page'))

drumbeatapp/templates/drumbeatapp/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">


    <head>


        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">


        <!-- Materialize -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

        <!-- CSS -->
        <link rel="stylesheet" href="{% static 'drumbeatapp/styles.css' %}">
        <!-- Font -->
        <link href="https://fonts.googleapis.com/css2?family=Fjalla+One&display=swap" rel="stylesheet">

        <title>Login</title>


    </head>


    <body>


        <div class="row">
            <div class="col s12">
                <div class="card blue-grey darken-1">
                    <div class="card-content white-text">
                        <span class="top_of_card">
                            <img src="https://cdn.iconscout.com/icon/premium/png-256-thumb/drums-78-833937.png" class="brand-logo">
                            <span class="drumbeat_card_header">DrumBeat</span>
                        </span>
                        <span class="card-title">Login</span>
                    </div>
                    <div class="card-action">
                        <form action="{% url 'drumbeatapp:login' %}" method="post">
                            {% csrf_token %}
                            <input type="text" name="username" placeholder="username"/>
                            <input type="password" name="password" placeholder="password"/>
                            <button type="submit">Login</button>
                            <a href="{% url 'drumbeatapp:register_page' %}">Register</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>


    </body>


</html>

drumbeatapp/templates/drumbeatapp/login_register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">


    <head>


        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">


        <!-- Materialize -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>


        <title>Login/Register</title>


    </head>


    <body>
        <div class="row">
            <div class="col s12 m6">
                <div class="card blue-grey darken-1">
                    <div class="card-content white-text">
                        <span class="card-title">Login</span>
                    </div>
                    <div class="card-action">
                        <form action="{% url 'drumbeatapp:login' %}" method="post">
                            {% csrf_token %}
                            <input type="text" name="username" placeholder="username"/>
                            <input type="password" name="password" placeholder="password"/>
                            <button type="submit">Login</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>


        <div class="row">
            <div class="col s12 m6">
                <div class="card blue-grey darken-1">
                    <div class="card-content white-text">
                        <span class="card-title">Register</span>
                    </div>
                    <div class="card-action">
                        <form action="{% url 'drumbeatapp:register' %}" method="post">
                            {% csrf_token %}
                            <input type="text" name="username" placeholder="username"/>
                            <input type="text" name="email" placeholder="email"/>
                            <input type="password" name="password" placeholder="password"/>
                            <button type="submit">Register</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>


        <!-- <h1>Login</h1>
        <form action="{% url 'drumbeatapp:login' %}" method="post">
            {% csrf_token %}
            <input type="text" name="username" placeholder="username"/>
            <input type="password" name="password" placeholder="password"/>
            <button type="submit">login</button>
        </form>


        <h1>Register</h1>
        <form action="{% url 'drumbeatapp:register' %}" method="post">
            {% csrf_token %}
            <input type="text" name="username" placeholder="username"/>
            <input type="text" name="email" placeholder="email"/>
            <input type="password" name="password" placeholder="password"/>
            <button type="submit">register</button>
        </form> -->


    </body>
</html>

drumbeatapp/templates/drumbeatapp/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">


    <head>


        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">


        <!-- Materialize -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

        <!-- CSS -->
        <link rel="stylesheet" href="{% static 'drumbeatapp/styles.css' %}">
        <!-- Font -->
        <link href="https://fonts.googleapis.com/css2?family=Fjalla+One&display=swap" rel="stylesheet">


        <title>Register</title>


    </head>


    <body>


        <div class="row">
            <div class="col s12">
                <div class="card blue-grey darken-1">
                    <div class="card-content white-text">
                        <span class="top_of_card">
                            <img src="https://cdn.iconscout.com/icon/premium/png-256-thumb/drums-78-833937.png" class="brand-logo">
                            <span class="drumbeat_card_header">DrumBeat</span>
                        </span>
                        <span class="card-title">Register</span>
                    </div>
                    <div class="card-action">
                        <form action="{% url 'drumbeatapp:register' %}" method="post">
                            {% csrf_token %}
                            <input type="text" name="username" placeholder="username"/>
                            <input type="text" name="email" placeholder="email"/>
                            <input type="password" name="password" placeholder="password"/>
                            <button type="submit">Register</button>
                            <a href="{% url 'drumbeatapp:login_page' %}">Login</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>


    </body>


</html>